project:
  type: website

website:
  title: "Freifecther Basel"
  favicon: assets/LOGO_SWISSHEMA.png
  page-navigation: true
  navbar:
    right:
      - icon: facebook
        href: "https://www.facebook.com/freifechterbasel/"
        aria-label: Facebook  
      - icon: instagram
        href: "https://www.instagram.com/freifechter_basel/"
        aria-label: Instagram  
  
profile: 
  group: 
    - [de,en,fr]

pre-render: generate-gallery.ts

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left


