project:
  output-dir: _site/fr
  type: website
  
  
website:
  title: "Freifechter Basel"
  navbar:
    left:
      - href: index.qmd
        text: Bienvenue!
      - href: gallery.qmd
        text: Gallerie
      - href: basilisk.qmd
        text: Basilisk Challenge
    right:
      - href: ../index.html
        text: Deutsch
      - href: index.html
        text: Fran√ßais
      - href: ../en/index.html
        text: English
