project:
  output-dir: _site/
  type: website
  

website:
  title: "Freifecther Basel"
  navbar:
    left:
      - href: index.qmd
        text: Hallo!
      - href: gallery.qmd
        text: Galerie
      - href: basilisk.qmd
        text: Basilisk Challenge
    right:
      - href: index.html
        text: Deutsch
      - href: en/index.html
        text: English